# Generated by Django 2.2.19 on 2022-02-25 14:54

import django.core.validators
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220221_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), api.models.min_cooking_time], verbose_name='Время приготовления'),
        ),
    ]
